#!/bin/sh -l

# Read JIT config generated by init container
if [ ! -f /mnt/reg-token-store/jit ]; then
  echo "ERROR: JIT config not found at /mnt/reg-token-store/jit"
  exit 1
fi

echo "INFO: Starting runner with JIT config"
JIT="$(cat /mnt/reg-token-store/jit)"
./run.sh --jitconfig "$JIT"
