#!/bin/bash
set -euo pipefail

JIT_TOKEN_PATH="${JIT_TOKEN_PATH:-/mnt/jit-token-store/jit}"

# Entrypoint logic

# Read JIT config generated by init container
if [ ! -f "$JIT_TOKEN_PATH" ]; then
  echo "ERROR: JIT config not found at $JIT_TOKEN_PATH"
  exit 1
fi

echo "INFO: Starting runner with JIT config"
JIT="$(cat "$JIT_TOKEN_PATH")" || {
  echo "ERROR: Failed to read JIT config from $JIT_TOKEN_PATH" >&2
  exit 1
}
./run.sh --jitconfig "$JIT"

